[versions]
agp = "8.13.0"
kotlin = "2.1.21"
composeBom = "2025.08.00"
activityCompose = "1.10.1"
room = "2.7.2"
datastore = "1.1.7"
glance = "1.1.1"
desugar = "2.1.5"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
